### ISSUE TITLE
签到时有错误，请问是怎么回事

### ISSUE THREAD

**Issue by wangshiw** [KaleoFeng/Misc#3]
签到时提示
"domain":
"weibo.com",

"url":
"https://weibo.com",

"message":
"超话签到[青岛黄海学院]: undefined-undefined",

"errno":
true

**Comment by kaleofeng** [comment]
信息太少，不好判断
请确保：
1. 目前该扩展chrome商城里的是过期版本，请使用zip格式本地安装
2. 保持微博为登录状态
3. 确保超话ID配置正确
